// var age = 15;
// if (age >= 18) {
//     console.log("YOU CAN VOTE");
// } else{
//     console.log(" YOU CAN NOT VOTE");
// }

// var birth = 1999;
// var age = 2021 - birth;
// if (age >= 18) {
//     console.log("YOU CAN VOTE");
// } else {
//     console.log(" YOU CAN NOT VOTE");
// }



// var char = "e";
// if (char == "i" || char == "o" || char == 'u' || char == "a" || char == "e") {
//     console.log("VOVELS")
// } else {
//     console.log("CONSONENT");
// }




// var code = 123467;
// if (code > 99999 && code < 1000000) {
// console.log("VALID")
// } else{
//     console.log("INVALID");
// }



//  var age11 = 18;
//  if (age11 < 18) {
//      console.log("you can not deive")
//  }
//  else if (age11 > 18) {
//      console.log("you can drive in india")
//  } else if (age11 == 18) {
//      console.log(" you just one day ago drive in india")
//  } else{

//  }



// var s_prise = 301;
// var dis = s_prise * 0.1;
// if (s_prise < 300) {
//     console.log("discount is O ");
// }
// else if (s_prise > 300 ) {
//     if (dis > 101) {
//         console.log("disount is 100rs")
//         } else{
//             console.log("discount is " + dis + "rs");
//         }
// }






// var height = 29.8;
// if (height < 18.5) {
//     console.log("you're in the underweight range");
// }
// else if (height > 18.5 && height < 24.9) {
//     console.log("you're in the healthy weight range");
// }
// else if (height > 25 && height < 29.9) {
//     console.log("you're in the overweight range");
// }
// else if (height > 30 && height < 39.9) {
//     console.log("you're in the obese range")
// }
// else{

// }


// var num21 = 21;
// (num21 % 2) == 0 ? console.log("EVEN") : console.log("ODD");



var year = 2016;

if (year % 4 == 0) {
    console.log("LEAP YEAR");
} else {
    console.log(" NOT LEAP YEAR");

}


