// Print "Hello Masai" on the console

console.log("Hello Masai");

// Print your by age by it storing in a variable
var age = 22;
console.log(age);

// Create a variable called name use it to print your name and your father's name

var name = "Shivam Singh";
var F_Name = "Badri Prasad Singh";
console.log(name);
console.log(F_Name);

// Given the side of the square calculate its area

var side = 11;
var area = side ** 2;
console.log(area);

// Given three variable print their sum

var num1 = 10;
var num2 = 100;
var num3 = 1000;
var sum = num1 + num2 + num3;
console.log(sum);

// Given a number find its square root

var num = 3;
var sq_root = num ** 0.5;
console.log(sq_root);

// Given two numbers in string format find their sum

var num1 = "12";
var num2 = "13";
var sum = num1 + num2;
console.log(sum);

// Given the certain number of chocolates find the number of chocolates left behind if equally distributed between 5 children

var chocolates = 33;
var child = 5;
var left_chocolates = chocolates % child;
console.log(left_chocolates);

// Given all the incomes from various sources find the total income
var income = 1000000;
var food = 12000;
var call = 13000;
var eat = 24230;
var num = 134235;
var total = income + food + call + eat + num;
console.log(total);